Blog start
ourgarage/blog pull request #1
Opened 2016-09-28 06:53 UTC by E-zh

2016-09-28 10:37 UTC, garf requested changes
Small comments.

2016-09-28 10:37 UTC, garf commented on README.md
>  * Run `php artisan vendor:publish`
Please add the additional parmeters. Ask @Anonim-khb

2016-09-28 10:37 UTC, garf commented on src/resources/assets/css/blog.css
> +}
Add one blank line below please

2016-09-28 10:37 UTC, garf commented on src/resources/assets/css/blog.css
> +  margin-top: 1em !important;
Do we need an `!important` here?

2016-09-28 10:37 UTC, garf commented on src/resources/assets/css/blog.less
> +.admin-dashboard {
Let's use 4-spaces indentation?

2016-09-28 10:37 UTC, garf commented on src/resources/assets/css/blog.less
> +  .blog-create {
Blank line below :)

2016-09-28 10:37 UTC, garf commented on src/resources/assets/css/blog.less
> +    .blog-index {
Let's separate every class declaraion with blank line. ;)

2016-09-28 10:37 UTC, garf commented on src/resources/views/admin/settings.blade.php
> +    @include('admin.basis.notifications-page')
Indentation :)

2016-09-28 22:06 UTC, E-zh commented on src/resources/assets/css/blog.less
> +.admin-dashboard {
It did Reformat code PhpStorm :)

2016-09-29 08:37 UTC, garf commented on src/resources/assets/css/blog.less
> +.admin-dashboard {
So you need to fix the format in Settings -> Editor -> Code Style :)

2016-09-29 11:51 UTC, garf commented on src/resources/views/admin/settings.blade.php
> +
Please remove line

2016-09-29 11:52 UTC, garf commented on src/resources/views/basis/css.blade.php
> +<link href='/packages/blog/css/blog.css' rel='stylesheet' type='text/css'>
Nope! :)
This file shouldn't be in global. What if blog is not installed?

2016-09-29 12:44 UTC, merged