Posts
ourgarage/blog pull request #4
Opened 2016-11-10 04:25 UTC by E-zh

2016-11-10 09:25 UTC, garf requested changes

2016-11-10 09:25 UTC, garf commented on src/Http/Requests/BlogPostRequest.php
> +    public function response(Array $errors)
`array`

2016-11-10 09:25 UTC, garf commented on src/database/migrations/2016_11_09_010435_create_posts_table.php
> +            $table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
Let's move indexed and constraints after fields creation.

2016-11-10 09:25 UTC, garf commented on src/database/migrations/2016_11_09_010435_create_posts_table.php
> +            $table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
And also let's don't use OnDelete. It will cause some problems :)

2016-11-10 09:25 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
Let's also add `DATETIME` field to DB, which will be called `published_at`. Will show posts whose `published_at` date is in the past.

2016-11-10 09:25 UTC, garf commented on src/database/migrations/2016_11_09_010435_create_posts_table.php
> +            $table->string('meta_title');
I also would add field `status` which will have values `draft`, `published`

2016-11-10 12:19 UTC, E-zh commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
Type of field `published_at` should be timestamp?

2016-11-10 12:25 UTC, E-zh commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
I maked type timestamp()

2016-11-10 12:48 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
Yes. Sure :)

2016-11-10 12:54 UTC, garf requested changes

2016-11-10 12:54 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
And here should be `where('published_at' '<=', <now>)`;

2016-11-10 12:54 UTC, garf commented on src/Models/Post.php
> +    const STATUS_DISABLED = 0;
I think disabled or published is not necessary. Active is already published. And Draft is already disabled. 
Or we just can leave Active and Disabled.

2016-11-10 12:54 UTC, garf commented on src/Models/Post.php
> +        'category_id', 'status', 'title', 'slug', 'content', 'meta_keywords', 'meta_description', 'meta_title'
`published_at` should be added here too.

2016-11-10 12:54 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +                                @if(isset($post))
How about putting only one foreach and check everything inside `option` tag?

2016-11-11 04:01 UTC, E-zh commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
`where('published_at', '<=', <now>);` It should be for users?

2016-11-11 08:26 UTC, garf requested changes

2016-11-11 08:26 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +                                   ? old('date_published', Carbon::parse($post->published_at)->format('d M Y'))
Let's use `Y-m-d H:i:s` format?
Because publish date also can have publish hours. i.e. if I want to publish this tomorrow at 3pm. :)

2016-11-11 08:26 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +        $('#date_published').datepicker({
Let me never see this anymore :)
Put all js code to `*,js` files. :)

2016-11-11 09:08 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::paginate(20);
Yes. You right. This is admin.
Here is all good :)

2016-11-11 14:27 UTC, garf commented on src/resources/views/admin/category/index.blade.php
> +                                <td>{{ $category->created_at->format('Y-m-d') }}</td>
Here you can leave df

2016-11-11 14:27 UTC, garf commented on src/resources/views/admin/post/index.blade.php
> +                                <td>{{ Carbon::parse($post->published_at)->format('Y-m-d') }}</td>
And here too

2016-11-11 14:27 UTC, garf commented on src/resources/views/admin/post/index.blade.php
> +                                <td>{{ $post->created_at->format('Y-m-d') }}</td>
And here

2016-11-11 14:27 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +                                   class="form-control" data-datepicker-params="{{ app()->getLocale() }}"
`data-datepicker-locale=""`

2016-11-16 12:47 UTC, garf approved these changes
Small comments :)

2016-11-16 12:47 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +                                   "format": "{{ trans('date.format.full.js') }}" }'
Here is 'full' And below is `long`. Is it correct?

2016-11-16 13:22 UTC, merged