Blog tags
ourgarage/blog pull request #6
Opened 2016-11-19 13:05 UTC by E-zh

2016-11-21 08:31 UTC, garf requested changes

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        $posts = Post::orderBy('id', 'desc')->paginate(20);
Better order by `published_at`

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +        // It's first version of code. It's we need?
https://laracasts.com/discuss/channels/eloquent/fetch-most-used-tags
Check this for most used tags fetching

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +            if (trim($tag) == '') {
You trimming them twice. Let's make it DRY :)

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +            $post_tag = new PostTags();
Why not using eloquent relation methods? 
Check this: https://laravel.com/docs/5.3/eloquent-relationships#inserting-and-updating-related-models

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/BlogController.php
> +    public function getTag(Tags $tags, $tag)
`getByTag`

2016-11-21 08:31 UTC, garf commented on src/Http/Controllers/BlogController.php
> +        if(!isset($tags)){
No need to this checks. Just select posts by tag. And if no posts, show that no posts. but not 404.

2016-11-21 08:31 UTC, garf commented on src/Models/Tags.php
> +    public static function popularTags($take)
What is this? :) Why it's static? :) Use it in normal way please.

2016-11-21 08:31 UTC, garf commented on src/database/migrations/2016_11_18_044430_create_post_tags_table.php
> +            $table->timestamps();
I think we don't need timestamps here.

2016-11-21 08:31 UTC, garf commented on src/database/migrations/2016_11_18_044430_create_post_tags_table.php
> +        Schema::dropIfExists('post_tags');
don't use `dropIfExists()`. Use `drop()` It should exist if migrations runned in correct way. Error will indicate us that something goes wrong with data structure.

2016-11-21 08:31 UTC, garf commented on src/database/migrations/2016_11_18_043230_create_tags_table.php
> +        Schema::dropIfExists('tags');
don't use `dropIfExists()`. Use `drop()`

2016-11-21 08:31 UTC, garf commented on src/resources/assets/js/post.js
> +$('.add-tag').on('click', function(){
space before `{`

2016-11-21 08:31 UTC, garf commented on src/resources/assets/js/post.js
> +    var inputTags = $('#inputTags');
prefix selectors with `$`
`$inputTags`

2016-11-21 08:31 UTC, garf commented on src/resources/assets/js/post.js
> +    $('#inputTags').tagsinput('add', newTag);
Use already created selector $inputTags.

2016-11-21 08:31 UTC, garf commented on src/resources/assets/js/post.js
> +var param = $('#date_published').data('datetimepicker-locale');
Why you keep in `data-datetimepicker-locale` something else than locale?

2016-11-21 08:31 UTC, garf commented on src/resources/views/admin/post/post.blade.php
> +                                       data-datetimepicker-locale='{"lang": "{{ app()->getLocale() }}",
Here. In `data-datetimepicker-locale` should be only locale info.
```
data-datetimepicker-locale="{{ app()->getLocale() }}"
data-datetimepicker-format="{{ trans('date.format.full.js') }}"

2016-11-24 13:25 UTC, E-zh commented on src/Http/Controllers/BlogController.php
> +        if(!isset($tags)){
This check is not post. If the tag is entered in the URL is not - we have to get 404. Or not?

2016-11-24 13:38 UTC, garf commented on src/Http/Controllers/BlogController.php
> +        if(!isset($tags)){
No. This is not the page with one record. We have a list of records here. So if no records, we show it. But not 404.

2016-11-28 09:30 UTC, garf commented on src/Http/Controllers/Admin/BlogPostController.php
> +    public function edit(Tags $tags, $id, Post $post)
Order of params should be adjusted. :)

2016-11-28 09:31 UTC, garf approved these changes

2016-11-28 11:11 UTC, merged